<?xml-stylesheet type='text/xsl' href='/template/html/error.html'?>
<error code='404'>Exception raised for view 'form_recomputation_results' [javax.xml.transform.TransformerConfigurationException: <xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><!-- generated by module html-template-engine --><xsl:output method="html"></xsl:output><xsl:template match="/"><html xmlns:tpl="http://software.in2p3.fr/lavoisier/template.xsd"><head>
    <meta charset="UTF-8"></meta>
    <title>ARGO</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"></meta>


    <xsl:comment> bootstrap 3.0.2 </xsl:comment>
    <link href="/resource/css/AdminLTE.css" rel="stylesheet"></link>
    <link href="/resource/css/bootstrap.min.css" rel="stylesheet"></link>
    <link href="/resource/css/font-awesome.css" rel="stylesheet"></link>
    <link href="/resource/css/ionicons.min.css" rel="stylesheet"></link>
    <link href="/resource/css/jquery-ui.css" rel="stylesheet"></link>
    <link href="/resource/css/bootstrap-timepicker.min.css" rel="stylesheet"></link>
    <link href="/resource/css/daterangepicker-bs3.css" rel="stylesheet" type="text/css"></link>
    <link href="/resource/css/multiselect.css" rel="stylesheet" type="text/css"></link>
    <link href="/resource/css/skin-argo.css" rel="stylesheet" type="text/css"></link>
    <link href="/resource/css/font-beba.css" rel="stylesheet" type="text/css"></link>

    <script src="/resource/js/jquery.min.js"></script>
    <script src="/resource/js/jquery-ui-1.10.3.js"></script>
    <script src="/resource/js/bootstrap.min.js"></script>
    <script src="/resource/js/multiselect.js" type="text/javascript"></script>


    <script src="/resource/js/jquery.dataTables.js"></script>
    <script src="/resource/js/dataTables.bootstrap.js"></script>
    <link href="/resource/css/dataTables.bootstrap.css" rel="stylesheet" type="text/css"></link>
    <link href="/resource/css/jquery.dataTables.css" rel="stylesheet" type="text/css"></link>


    <script src="/resource/js/app.js"></script>
    <script src="/resource/js/scripts.js"></script>

    <link href="/resource/img/favicon.ico" rel="shortcut icon"></link>


    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-65947937-1', 'auto');
        ga('send', 'pageview');

    </script>
</head><aside class="control-sidebar control-sidebar-dark">


    <div class="tab-content">

        <h3 class="control-sidebar-heading">Release</h3>

        <ul class="control-sidebar-menu">
            <li>
                <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Version:</h4>
                    <p>2.0</p>
                </div>
            </li>
            <li>
                <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Date:</h4>
                    <p>2015, September 23th</p>
                </div>
            </li>
            <li>
                <div class="menu-info">
                    <h4 class="control-sidebar-subheading"> Repository
                        <a href="https://github.com/ARGOeu"> <span class="fa fa-github" style="font-size: larger"> </span></a></h4>
                </div>

            </li>
        </ul>


    </div>





</aside>

    <body class="skin-blue sidebar-mini">
        <xsl:comment> Right side column. Contains the navbar and content of the page </xsl:comment>
        <div class="wrapper" id="wrapper"><header class="main-header">






            <xsl:comment> Header Navbar: style can be found in header.less </xsl:comment>
            <nav class="navbar navbar-static-top" role="navigation">
                <xsl:comment> Sidebar toggle button</xsl:comment>
                <a class="sidebar-toggle" data-toggle="offcanvas" href="#" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <a class="navbar-brand" href="/lavoisier" ib="brand"><img alt="Argo" src="/resource/img/logo.png"></img></a>
                <xsl:comment> Navbar Right Menu </xsl:comment>
                <div class="navbar-custom-menu navbar-collapse collapse">


                    <ul class="nav navbar-nav">


                        <xsl:comment> Control Sidebar Toggle Button </xsl:comment>
                        <li class="active"><a href="#">ARGO WEB UI</a></li>

                    </ul>
                </div>

            </nav>



        </header><aside class="main-sidebar sidebar-offcanvas">

            <section class="sidebar">



                <ul class="sidebar-menu">

                    <xsl:for-each select="/menu/categories"><li class="treeview" id="sidebar-menu">
                        <a href="#">
                            <i class="{@icon}"></i> <span><xsl:value-of select="@title"></xsl:value-of></span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <xsl:for-each select="category"><li><a href="{@link}"><i class="{@icon}"></i><xsl:value-of select="text()"></xsl:value-of></a></li></xsl:for-each>

                        </ul>
                    </li></xsl:for-each>


                </ul>

            </section>
            <xsl:comment> /.sidebar </xsl:comment>
        </aside>
            <xsl:comment> Left side column. contains the logo and sidebar </xsl:comment>
            <aside class="main-sidebar sidebar-offcanvas" id="left-side">
                <section class="sidebar">
                    <ul class="sidebar-menu"><xsl:for-each select="/menu/categories"><li class="treeview" id="sidebar-menu">
                        <a href="#">
                            <i class="{@icon}"></i> <span><xsl:value-of select="@title"></xsl:value-of></span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <xsl:for-each select="category"><li><a href="{@link}"><i class="{@icon}"></i><xsl:value-of select="text()"></xsl:value-of></a></li></xsl:for-each>

                        </ul>
                    </li></xsl:for-each>

                        <li>
                            <a href="/lavoisier">
                                <i class="fa fa-home"></i>Homepage
                            </a>
                        </li>
                    </ul>
                </section>
            </aside>

            <xsl:comment> Content Header (Page header) </xsl:comment>
            <div class="content-wrapper"><section class="content" id="content">

                <section class="content-header" id="content-header">
                    <h1>
                        Home Page
                        <small>Start page</small>
                    </h1>

                </section>


            </section>


                <section class="content-header" id="content-header">
                    <h1>
                        Recomputation
                        <small>Management page</small>
                    </h1>
                    <ol class="breadcrumb" id="breadcrumb">
                        <li><a href="#"><i class="fa fa-dashboard"></i> Recomputation Management</a></li>
                        <li class="active">Index</li>
                    </ol>
                </section>

                <div class="alert alert-info">
                    Your request has been successfully submitted (details below)<br></br>
                    You should wait now for the validation and will be informed by email .
                </div>
                <br></br><br></br>

                <table class="table table-bordered table-condensed table-striped ">
                    <xsl:for-each select="e:entries/e:entry"><tr>
                        <th><xsl:value-of select="@key"></xsl:value-of></th>
                        <td><xsl:value-of select="text()"></xsl:value-of></td>
                    </tr></xsl:for-each>

                </table>


                <xsl:comment> /.content </xsl:comment>
            </div>

        </div>
    </body>
</html></xsl:template><xsl:template name="process-token"><xsl:param name="token"></xsl:param><xsl:param name="position"></xsl:param><xsl:param name="last"></xsl:param><xsl:param name="callback"></xsl:param><xsl:choose><xsl:when test="false()"></xsl:when></xsl:choose></xsl:template><xsl:template name="tokenize">
    <xsl:param name="string"></xsl:param>
    <xsl:param name="delimiter"></xsl:param>
    <xsl:param name="callback"></xsl:param>
    <xsl:param name="position">1</xsl:param>
    <xsl:choose>
        <xsl:when test="contains($string, $delimiter)">
            <xsl:call-template name="process-token">
                <xsl:with-param name="token" select="substring-before($string, $delimiter)"></xsl:with-param>
                <xsl:with-param name="position" select="$position"></xsl:with-param>
                <xsl:with-param name="last" select="false()"></xsl:with-param>
                <xsl:with-param name="callback" select="$callback"></xsl:with-param>
            </xsl:call-template>
            <xsl:call-template name="tokenize">
                <xsl:with-param name="string" select="substring-after($string, $delimiter)"></xsl:with-param>
                <xsl:with-param name="delimiter" select="$delimiter"></xsl:with-param>
                <xsl:with-param name="callback" select="$callback"></xsl:with-param>
                <xsl:with-param name="position" select="$position + 1"></xsl:with-param>
            </xsl:call-template>
        </xsl:when>
        <xsl:otherwise>
            <xsl:call-template name="process-token">
                <xsl:with-param name="token" select="$string"></xsl:with-param>
                <xsl:with-param name="position" select="$position"></xsl:with-param>
                <xsl:with-param name="last" select="true()"></xsl:with-param>
                <xsl:with-param name="callback" select="$callback"></xsl:with-param>
            </xsl:call-template>
        </xsl:otherwise>
    </xsl:choose>
</xsl:template><xsl:template match="*" mode="serialize">
    <xsl:param name="indent"><xsl:text>
    </xsl:text></xsl:param>
    <xsl:if test="string-length($indent)&gt;1"><xsl:value-of select="$indent"></xsl:value-of></xsl:if>&lt;<xsl:value-of select="name()"></xsl:value-of>
    <xsl:apply-templates mode="serialize" select="@*"></xsl:apply-templates>
    <xsl:choose>
        <xsl:when test="*">&gt;<xsl:text></xsl:text>
            <xsl:apply-templates mode="serialize"><xsl:with-param name="indent" select="concat($indent,&apos;    &apos;)"></xsl:with-param></xsl:apply-templates>
            <xsl:value-of select="$indent"></xsl:value-of>&lt;/<xsl:value-of select="name()"></xsl:value-of>&gt;<xsl:text></xsl:text>
        </xsl:when>
        <xsl:when test="text()|comment()">&gt;<xsl:apply-templates mode="serialize"></xsl:apply-templates>&lt;/<xsl:value-of select="name()"></xsl:value-of>&gt;</xsl:when>
        <xsl:otherwise>/&gt;</xsl:otherwise>
    </xsl:choose>
</xsl:template><xsl:template match="@*" mode="serialize">
    <xsl:text> </xsl:text><xsl:value-of select="name()"></xsl:value-of>="<xsl:value-of select="."></xsl:value-of>"<xsl:text></xsl:text>
</xsl:template><xsl:template match="text()" mode="serialize">
    <xsl:value-of select="normalize-space(.)"></xsl:value-of>
</xsl:template><xsl:template match="comment()" mode="serialize">
    <xsl:comment><xsl:value-of select="."></xsl:value-of></xsl:comment>
</xsl:template></xsl:stylesheet>]</error>
